version: '3.8'
services:
  database:
    image: mysql:8.0.36
    restart: unless-stopped
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=$password
    ports:
      - $DB_PORT_LOCAL:$DB_PORT_DOCKER
  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - port=$port
      - host=$host
      - user=$user
      - password=$password
      - database=$database
      - DB_PORT_LOCAL=$DB_PORT_LOCAL
      - secretTokenKey=$secretTokenKey
      - clientDomain=$clientDomain
      - API_URL=$API_URL
      - app_id=$app_id
      - key1=$key1
      - key2=$key2
      - endpointCreate=$endpointCreate
      - endpointQueryStatus=$endpointQueryStatus
      - emailPassword=$emailPassword
      - emailUser=$emailUser
    ports:
      - $port:3000
  frontend:
      build:
        context: ./frontend
        args:
          - VITE_API_URL=$API_URL
      restart: unless-stopped
      ports:
          - '80:80'